name: my_time

version: 1.0.4+8

publish_to: none

description: A new Flutter project.

environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  dio: ^5.3.1
  flutter: 
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations: 
    sdk: flutter
  flutter_markdown: ^0.6.17
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.7
  intl: ^0.18.0
  realm: ^1.3.0
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  snappy_list_view: ^0.1.0
  uuid: ^3.0.7

dev_dependencies: 
  build_runner: ^2.4.6
  dart_pre_commit: ^5.2.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.1
  git_hooks: ^1.0.1
  pubspec_dependency_sorter: ^1.0.3
  rename: ^2.1.1
  riverpod_generator: ^2.2.4
  very_good_analysis: ^5.0.0+1

flutter_icons: 
  image_path: assets/app_icon.png
  adaptive_icon_foreground: assets/ic_launcher_foreground.png
  adaptive_icon_background: '#ffffff'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash: 
  color: '#fadeb4'
  image: assets/splash_image.png
  android_12: 
    image: assets/play_store_512.png
    color: '#fadeb4'
  android: true
  ios: true
  
flutter: 
  assets: 
    - assets/
  generate: true
  uses-material-design: true
