name: my_time

version: 1.0.4+8

publish_to: none

description: A new Flutter project.

environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  clock: ^1.1.1
  dart_pre_commit: ^5.2.0+1
  dio: ^5.3.3
  flutter: 
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_localizations: 
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  git_hooks: ^1.0.1
  go_router: ^11.0.0
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  realm: ^1.5.0
  riverpod_annotation: ^2.1.5
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  snappy_list_view: ^0.1.0
  uuid: ^3.0.7

dev_dependencies: 
  build_runner: ^2.4.6
  dlcov: ^4.2.1
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  patrol_finders: ^1.0.0
  process_run: ^0.13.1
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.3.2
  very_good_analysis: ^5.1.0

dart_pre_commit:
  outdated:
    level: major

flutter_icons: 
  image_path: assets/app_icon.png
  adaptive_icon_foreground: assets/ic_launcher_foreground.png
  adaptive_icon_background: '#ffffff'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash: 
  color: '#fadeb4'
  image: assets/splash_image.png
  android_12: 
    image: assets/play_store_512.png
    color: '#fadeb4'
  android: true
  ios: true
  
flutter: 
  assets: 
    - assets/
  generate: true
  uses-material-design: true
