name: Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Set up key.properties
      run: |
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "${{ secrets.STORE_FILE_CONTENT }}" | base64 --decode > android/key.jks

    - name: Set up Play Store Secret
      run: |
        echo "${{ secrets.PLAY_STORE_SECRET }}" | base64 --decode > android/myTime_play_store_credentials.json

    - name: Setup Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        rubygems: latest

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle' 

    - name: Get Dependencies
      run: |
        flutter clean
        flutter pub get
       
    - name: Build App Bundle
      run: |
        flutter build appbundle    

    - name: Deploy
      run: |
        cd android && bundle exec fastlane playstore