name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 3
  workflow_dispatch:

# 4
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        


      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run unit tests
        run: flutter test --coverage

        
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: "12.x"
      #     cache: 'gradle'     


      # Runs a set of commands using the runners shell
      # - name: Start release build
      #   run: flutter build appbundle
